const mongoose = require('mongoose');
require('dotenv').config();

// Import models
const User = require('./models/User');
const Item = require('./models/Item');

// Connect to MongoDB
mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost:27017/ecocloset")
  .then(() => console.log("MongoDB Connected"))
  .catch(err => console.log(err));

async function add100Items() {
  try {
    // Get or create demo user
    let user = await User.findOne({ email: 'demo@ecocloset.com' });
    
    if (!user) {
      const bcrypt = require('bcryptjs');
      const salt = bcrypt.genSaltSync(12);
      
      user = new User({
        username: 'demouser',
        email: 'demo@ecocloset.com',
        password: bcrypt.hashSync('demo123', salt),
        firstName: 'Demo',
        lastName: 'User',
        role: 'user'
      });
      
      await user.save({ validateBeforeSave: false });
      console.log('Demo user created');
    }

    // Comprehensive 100 items collection
    const items100 = [
      // SHIRTS (15 items)
      {
        title: "Classic White Oxford Shirt",
        description: "Timeless white oxford shirt perfect for professional and casual wear. Made from sustainable cotton.",
        category: "shirts",
        size: "m",
        condition: "like_new",
        type: "both",
        brand: "Brooks Brothers",
        materials: ["organic_cotton"],
        color: "white",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1596755094587-5e0244e83d2e?w=400"],
        owner: user._id,
        tags: ["formal", "classic", "sustainable", "versatile"],
        status: "available"
      },
      {
        title: "Vintage Band T-Shirt",
        description: "Classic rock band t-shirt from the 90s. Great condition with minimal wear.",
        category: "shirts",
        size: "l",
        condition: "good",
        type: "swap",
        brand: "Various",
        materials: ["cotton"],
        color: "black",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1521572163464-7535f5453c2a?w=400"],
        owner: user._id,
        tags: ["vintage", "band", "casual", "retro"],
        status: "available"
      },
      {
        title: "Linen Summer Shirt",
        description: "Breathable linen shirt perfect for hot weather. Natural fibers and eco-friendly.",
        category: "shirts",
        size: "s",
        condition: "new",
        type: "both",
        brand: "Uniqlo",
        materials: ["linen"],
        color: "beige",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1594933886957-4f5b5c6d1c2e?w=400"],
        owner: user._id,
        tags: ["summer", "linen", "breathable", "eco-friendly"],
        status: "available"
      },
      {
        title: "Plaid Flannel Shirt",
        description: "Cozy plaid flannel shirt perfect for autumn. Made from recycled materials.",
        category: "shirts",
        size: "l",
        condition: "good",
        type: "swap",
        brand: "Patagonia",
        materials: ["recycled_cotton"],
        color: "red_plaid",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1576871335924-2e6c8b8b5b3c?w=400"],
        owner: user._id,
        tags: ["flannel", "autumn", "cozy", "recycled"],
        status: "available"
      },
      {
        title: "Hemp Fiber T-Shirt",
        description: "Eco-friendly t-shirt made from sustainable hemp fibers. Naturally antimicrobial.",
        category: "shirts",
        size: "m",
        condition: "new",
        type: "donation",
        brand: "Thought",
        materials: ["hemp"],
        color: "green",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1521572163464-7535f5453c2a?w=400"],
        owner: user._id,
        tags: ["hemp", "sustainable", "eco-friendly", "natural"],
        status: "available"
      },
      {
        title: "Chambray Work Shirt",
        description: "Classic chambray work shirt with vintage styling. Durable and timeless.",
        category: "shirts",
        size: "l",
        condition: "like_new",
        type: "both",
        brand: "Carhartt",
        materials: ["cotton"],
        color: "blue",
        sustainabilityScore: 7,
        images: ["https://images.unsplash.com/photo-1596755094587-5e0244e83d2e?w=400"],
        owner: user._id,
        tags: ["work", "vintage", "durable", "classic"],
        status: "available"
      },
      {
        title: "Organic Cotton Polo Shirt",
        description: "Classic polo shirt made from certified organic cotton. Perfect for casual wear.",
        category: "shirts",
        size: "m",
        condition: "good",
        type: "swap",
        brand: "Ralph Lauren",
        materials: ["organic_cotton"],
        color: "navy",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1576871335924-2e6c8b8b5b3c?w=400"],
        owner: user._id,
        tags: ["polo", "classic", "organic", "casual"],
        status: "available"
      },
      {
        title: "Tencel Button-Up Shirt",
        description: "Modern button-up shirt made from Tencel fabric. Sustainable and incredibly soft.",
        category: "shirts",
        size: "s",
        condition: "new",
        type: "both",
        brand: "Everlane",
        materials: ["tencel"],
        color: "white",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1596755094587-5e0244e83d2e?w=400"],
        owner: user._id,
        tags: ["tencel", "modern", "sustainable", "soft"],
        status: "available"
      },
      {
        title: "Vintage Western Shirt",
        description: "Authentic western shirt with pearl snaps. Classic American style.",
        category: "shirts",
        size: "l",
        condition: "good",
        type: "swap",
        brand: "Wrangler",
        materials: ["cotton"],
        color: "brown",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1576871335924-2e6c8b8b5b3c?w=400"],
        owner: user._id,
        tags: ["western", "vintage", "classic", "american"],
        status: "available"
      },
      {
        title: "Bamboo Fiber Shirt",
        description: "Ultra-soft shirt made from bamboo fibers. Naturally hypoallergenic.",
        category: "shirts",
        size: "m",
        condition: "like_new",
        type: "donation",
        brand: "Boody",
        materials: ["bamboo"],
        color: "gray",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1521572163464-7535f5453c2a?w=400"],
        owner: user._id,
        tags: ["bamboo", "soft", "hypoallergenic", "sustainable"],
        status: "available"
      },
      {
        title: "Recycled Polyester Athletic Shirt",
        description: "Performance athletic shirt made from recycled plastic bottles.",
        category: "shirts",
        size: "l",
        condition: "new",
        type: "both",
        brand: "Nike",
        materials: ["recycled_polyester"],
        color: "blue",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1576871335924-2e6c8b8b5b3c?w=400"],
        owner: user._id,
        tags: ["athletic", "recycled", "performance", "eco-friendly"],
        status: "available"
      },
      {
        title: "Corduroy Shirt",
        description: "Vintage corduroy shirt with warm texture. Perfect for cooler weather.",
        category: "shirts",
        size: "m",
        condition: "good",
        type: "swap",
        brand: "Gap",
        materials: ["cotton", "corduroy"],
        color: "tan",
        sustainabilityScore: 7,
        images: ["https://images.unsplash.com/photo-1596755094587-5e0244e83d2e?w=400"],
        owner: user._id,
        tags: ["corduroy", "vintage", "warm", "casual"],
        status: "available"
      },
      {
        title: "Organic Henley Shirt",
        description: "Comfortable henley shirt made from organic cotton. Versatile layering piece.",
        category: "shirts",
        size: "l",
        condition: "like_new",
        type: "both",
        brand: "American Apparel",
        materials: ["organic_cotton"],
        color: "gray",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1576871335924-2e6c8b8b5b3c?w=400"],
        owner: user._id,
        tags: ["henley", "organic", "versatile", "comfortable"],
        status: "available"
      },
      {
        title: "Tie-Dye T-Shirt",
        description: "Hand-dyed tie-dye t-shirt with vibrant colors. Unique artistic design.",
        category: "shirts",
        size: "s",
        condition: "new",
        type: "donation",
        brand: "Handmade",
        materials: ["cotton"],
        color: "multicolor",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1521572163464-7535f5453c2a?w=400"],
        owner: user._id,
        tags: ["tie-dye", "artistic", "unique", "colorful"],
        status: "available"
      },
      {
        title: "Recycled Denim Shirt",
        description: "Stylish shirt made from recycled denim. Sustainable fashion choice.",
        category: "shirts",
        size: "m",
        condition: "good",
        type: "swap",
        brand: "Reformation",
        materials: ["recycled_denim"],
        color: "blue",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1596755094587-5e0244e83d2e?w=400"],
        owner: user._id,
        tags: ["recycled", "denim", "sustainable", "stylish"],
        status: "available"
      },

      // PANTS (15 items)
      {
        title: "Slim Fit Chino Pants",
        description: "Versatile slim-fit chinos in khaki color. Perfect for office and casual occasions.",
        category: "pants",
        size: "m",
        condition: "like_new",
        type: "both",
        brand: "Dockers",
        materials: ["cotton"],
        color: "khaki",
        sustainabilityScore: 7,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["formal", "versatile", "classic", "comfortable"],
        status: "available"
      },
      {
        title: "Vintage Denim Jeans",
        description: "Classic 501 style denim jeans with authentic vintage wash. Great for sustainable fashion.",
        category: "pants",
        size: "l",
        condition: "good",
        type: "swap",
        brand: "Levi's",
        materials: ["denim", "cotton"],
        color: "blue",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400"],
        owner: user._id,
        tags: ["vintage", "denim", "classic", "durable"],
        status: "available"
      },
      {
        title: "Recycled Polyester Joggers",
        description: "Comfortable joggers made from recycled materials. Perfect for lounging and light exercise.",
        category: "pants",
        size: "m",
        condition: "new",
        type: "donation",
        brand: "Patagonia",
        materials: ["recycled_polyester"],
        color: "gray",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["recycled", "comfortable", "athletic", "eco-friendly"],
        status: "available"
      },
      {
        title: "Wool Dress Pants",
        description: "Professional wool dress pants perfect for business meetings. Classic tailoring.",
        category: "pants",
        size: "l",
        condition: "like_new",
        type: "both",
        brand: "Banana Republic",
        materials: ["wool"],
        color: "charcoal",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["formal", "wool", "professional", "classic"],
        status: "available"
      },
      {
        title: "Organic Cotton Cargo Pants",
        description: "Functional cargo pants made from organic cotton. Multiple pockets for utility.",
        category: "pants",
        size: "m",
        condition: "good",
        type: "swap",
        brand: "Prana",
        materials: ["organic_cotton"],
        color: "olive",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["cargo", "organic", "functional", "outdoor"],
        status: "available"
      },
      {
        title: "Linen Summer Pants",
        description: "Lightweight linen pants perfect for hot weather. Breathable and comfortable.",
        category: "pants",
        size: "s",
        condition: "new",
        type: "donation",
        brand: "J.Crew",
        materials: ["linen"],
        color: "beige",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["linen", "summer", "breathable", "lightweight"],
        status: "available"
      },
      {
        title: "Recycled Swim Trunks",
        description: "Eco-friendly swim trunks made from recycled ocean plastic. Quick-drying fabric.",
        category: "pants",
        size: "l",
        condition: "new",
        type: "both",
        brand: "Speedo",
        materials: ["recycled_polyester"],
        color: "blue",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["swim", "recycled", "ocean_plastic", "quick_dry"],
        status: "available"
      },
      {
        title: "Hemp Fiber Jeans",
        description: "Sustainable jeans made from hemp fibers. Durable and environmentally friendly.",
        category: "pants",
        size: "m",
        condition: "good",
        type: "swap",
        brand: "Thought",
        materials: ["hemp", "cotton"],
        color: "indigo",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400"],
        owner: user._id,
        tags: ["hemp", "sustainable", "jeans", "eco-friendly"],
        status: "available"
      },
      {
        title: "Tencel Wide Leg Pants",
        description: "Flowing wide leg pants made from Tencel fabric. Elegant and sustainable.",
        category: "pants",
        size: "s",
        condition: "like_new",
        type: "donation",
        brand: "Everlane",
        materials: ["tencel"],
        color: "black",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["tencel", "wide_leg", "elegant", "sustainable"],
        status: "available"
      },
      {
        title: "Vintage Corduroy Pants",
        description: "Retro corduroy pants with warm texture. Perfect for autumn and winter.",
        category: "pants",
        size: "l",
        condition: "good",
        type: "swap",
        brand: "Gap",
        materials: ["cotton", "corduroy"],
        color: "brown",
        sustainabilityScore: 7,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["corduroy", "vintage", "warm", "retro"],
        status: "available"
      },
      {
        title: "Recycled Wool Trousers",
        description: "Professional trousers made from recycled wool. Sustainable business wear.",
        category: "pants",
        size: "m",
        condition: "new",
        type: "both",
        brand: "Reformation",
        materials: ["recycled_wool"],
        color: "navy",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["recycled", "wool", "professional", "sustainable"],
        status: "available"
      },
      {
        title: "Bamboo Yoga Pants",
        description: "Comfortable yoga pants made from bamboo fabric. Naturally antimicrobial.",
        category: "pants",
        size: "s",
        condition: "like_new",
        type: "donation",
        brand: "Boody",
        materials: ["bamboo"],
        color: "purple",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["yoga", "bamboo", "comfortable", "athletic"],
        status: "available"
      },
      {
        title: "Organic Cotton Overalls",
        description: "Vintage-style overalls made from organic cotton. Practical and sustainable.",
        category: "pants",
        size: "m",
        condition: "good",
        type: "swap",
        brand: "Carhartt",
        materials: ["organic_cotton"],
        color: "blue",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["overalls", "organic", "practical", "workwear"],
        status: "available"
      },
      {
        title: "Recycled Leather Pants",
        description: "Fashionable pants made from recycled leather. Sustainable luxury fashion.",
        category: "pants",
        size: "s",
        condition: "new",
        type: "donation",
        brand: "Stella McCartney",
        materials: ["recycled_leather"],
        color: "black",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["recycled", "leather", "luxury", "fashionable"],
        status: "available"
      },
      {
        title: "Hemp Cargo Shorts",
        description: "Durable cargo shorts made from hemp fabric. Perfect for summer adventures.",
        category: "pants",
        size: "l",
        condition: "good",
        type: "swap",
        brand: "Patagonia",
        materials: ["hemp"],
        color: "khaki",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
        owner: user._id,
        tags: ["shorts", "hemp", "cargo", "summer"],
        status: "available"
      },

      // DRESSES (15 items)
      {
        title: "Floral Summer Maxi Dress",
        description: "Beautiful flowing maxi dress with floral print. Perfect for summer events and beach outings.",
        category: "dresses",
        size: "m",
        condition: "like_new",
        type: "both",
        brand: "Free People",
        materials: ["rayon", "cotton"],
        color: "floral",
        sustainabilityScore: 7,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["summer", "floral", "bohemian", "comfortable"],
        status: "available"
      },
      {
        title: "Little Black Dress",
        description: "Timeless little black dress perfect for formal occasions. Classic and elegant design.",
        category: "dresses",
        size: "s",
        condition: "like_new",
        type: "swap",
        brand: "Zara",
        materials: ["organic_cotton"],
        color: "black",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["formal", "classic", "elegant", "versatile"],
        status: "available"
      },
      {
        title: "Organic Cotton Sundress",
        description: "Eco-friendly sundress made from certified organic cotton. Perfect for sustainable summer fashion.",
        category: "dresses",
        size: "l",
        condition: "new",
        type: "donation",
        brand: "Eileen Fisher",
        materials: ["organic_cotton"],
        color: "yellow",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["organic", "summer", "sustainable", "comfortable"],
        status: "available"
      },
      {
        title: "Tencel Slip Dress",
        description: "Elegant slip dress made from Tencel fabric. Sustainable luxury with beautiful drape.",
        category: "dresses",
        size: "s",
        condition: "new",
        type: "both",
        brand: "Reformation",
        materials: ["tencel"],
        color: "champagne",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["tencel", "slip_dress", "luxury", "sustainable"],
        status: "available"
      },
      {
        title: "Vintage Polka Dot Dress",
        description: "Retro polka dot dress from the 1950s. Classic feminine style with sustainable materials.",
        category: "dresses",
        size: "m",
        condition: "good",
        type: "swap",
        brand: "Vintage",
        materials: ["cotton"],
        color: "red_white",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["vintage", "polka_dot", "retro", "feminine"],
        status: "available"
      },
      {
        title: "Hemp Fiber Summer Dress",
        description: "Breathable summer dress made from sustainable hemp fibers. Naturally UV resistant.",
        category: "dresses",
        size: "l",
        condition: "like_new",
        type: "donation",
        brand: "Thought",
        materials: ["hemp"],
        color: "green",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["hemp", "summer", "breathable", "sustainable"],
        status: "available"
      },
      {
        title: "Recycled Polyester Evening Gown",
        description: "Elegant evening gown made from recycled materials. Sustainable formal wear.",
        category: "dresses",
        size: "s",
        condition: "new",
        type: "both",
        brand: "Stella McCartney",
        materials: ["recycled_polyester"],
        color: "navy",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["evening", "formal", "recycled", "luxury"],
        status: "available"
      },
      {
        title: "Linen Wrap Dress",
        description: "Classic wrap dress made from breathable linen. Perfect for spring and summer.",
        category: "dresses",
        size: "m",
        condition: "good",
        type: "swap",
        brand: "Eileen Fisher",
        materials: ["linen"],
        color: "white",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["wrap_dress", "linen", "versatile", "classic"],
        status: "available"
      },
      {
        title: "Bamboo Fiber Midi Dress",
        description: "Comfortable midi dress made from bamboo fabric. Naturally soft and hypoallergenic.",
        category: "dresses",
        size: "l",
        condition: "new",
        type: "donation",
        brand: "Boody",
        materials: ["bamboo"],
        color: "coral",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["midi", "bamboo", "comfortable", "hypoallergenic"],
        status: "available"
      },
      {
        title: "Vintage Lace Wedding Dress",
        description: "Beautiful vintage lace wedding dress with sustainable materials. Timeless elegance.",
        category: "dresses",
        size: "s",
        condition: "like_new",
        type: "both",
        brand: "Vintage",
        materials: ["cotton", "lace"],
        color: "ivory",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["wedding", "vintage", "lace", "bridal"],
        status: "available"
      },
      {
        title: "Recycled Denim Pinafore Dress",
        description: "Casual pinafore dress made from recycled denim. Sustainable and stylish.",
        category: "dresses",
        size: "m",
        condition: "good",
        type: "swap",
        brand: "Reformation",
        materials: ["recycled_denim"],
        color: "blue",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["pinafore", "recycled", "denim", "casual"],
        status: "available"
      },
      {
        title: "Organic Cotton Shift Dress",
        description: "Simple shift dress made from organic cotton. Minimalist and sustainable.",
        category: "dresses",
        size: "l",
        condition: "new",
        type: "donation",
        brand: "Everlane",
        materials: ["organic_cotton"],
        color: "black",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["shift_dress", "minimalist", "organic", "versatile"],
        status: "available"
      },
      {
        title: "Tencel Beach Cover-Up",
        description: "Lightweight beach cover-up made from Tencel. Perfect for sustainable beach days.",
        category: "dresses",
        size: "s",
        condition: "like_new",
        type: "both",
        brand: "Patagonia",
        materials: ["tencel"],
        color: "white",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["beach", "cover_up", "tencel", "lightweight"],
        status: "available"
      },
      {
        title: "Vintage 70s Maxi Dress",
        description: "Authentic 1970s maxi dress with psychedelic print. Groovy sustainable fashion.",
        category: "dresses",
        size: "m",
        condition: "good",
        type: "swap",
        brand: "Vintage",
        materials: ["cotton"],
        color: "psychedelic",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["vintage", "70s", "psychedelic", "maxi"],
        status: "available"
      },
      {
        title: "Recycled Silk Evening Dress",
        description: "Luxurious evening dress made from recycled silk. Sustainable glamour.",
        category: "dresses",
        size: "s",
        condition: "new",
        type: "donation",
        brand: "Reformation",
        materials: ["recycled_silk"],
        color: "emerald",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["evening", "silk", "recycled", "luxury"],
        status: "available"
      },
      {
        title: "Organic Cotton Baby Doll Dress",
        description: "Cute baby doll dress made from organic cotton. Feminine and sustainable.",
        category: "dresses",
        size: "l",
        condition: "like_new",
        type: "both",
        brand: "Free People",
        materials: ["organic_cotton"],
        color: "pink",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1539008895308-32bf5c846a2c?w=400"],
        owner: user._id,
        tags: ["baby_doll", "organic", "feminine", "cute"],
        status: "available"
      },

      // JACKETS (15 items)
      {
        title: "Classic Denim Jacket",
        description: "Iconic denim jacket with vintage wash. Perfect layering piece for any season.",
        category: "jackets",
        size: "m",
        condition: "good",
        type: "both",
        brand: "Levi's",
        materials: ["denim", "cotton"],
        color: "blue",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["classic", "denim", "versatile", "durable"],
        status: "available"
      },
      {
        title: "Wool Pea Coat",
        description: "Classic navy wool pea coat perfect for winter. Timeless style with excellent warmth.",
        category: "jackets",
        size: "l",
        condition: "like_new",
        type: "swap",
        brand: "J.Crew",
        materials: ["wool", "recycled_polyester"],
        color: "navy",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["winter", "formal", "classic", "warm"],
        status: "available"
      },
      {
        title: "Recycled Windbreaker",
        description: "Lightweight windbreaker made from recycled materials. Perfect for outdoor activities.",
        category: "jackets",
        size: "s",
        condition: "new",
        type: "donation",
        brand: "Patagonia",
        materials: ["recycled_polyester"],
        color: "green",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["recycled", "outdoor", "lightweight", "eco-friendly"],
        status: "available"
      },
      {
        title: "Leather Motorcycle Jacket",
        description: "Classic leather motorcycle jacket with vintage styling. Durable and timeless.",
        category: "jackets",
        size: "m",
        condition: "good",
        type: "both",
        brand: "Schott",
        materials: ["leather"],
        color: "black",
        sustainabilityScore: 6,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["motorcycle", "leather", "vintage", "durable"],
        status: "available"
      },
      {
        title: "Hemp Fiber Canvas Jacket",
        description: "Durable canvas jacket made from sustainable hemp fibers. Perfect for workwear.",
        category: "jackets",
        size: "l",
        condition: "like_new",
        type: "swap",
        brand: "Patagonia",
        materials: ["hemp", "canvas"],
        color: "brown",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["hemp", "canvas", "workwear", "durable"],
        status: "available"
      },
      {
        title: "Recycled Puffer Jacket",
        description: "Warm puffer jacket made from recycled materials. Sustainable winter warmth.",
        category: "jackets",
        size: "m",
        condition: "new",
        type: "donation",
        brand: "The North Face",
        materials: ["recycled_polyester"],
        color: "black",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["puffer", "recycled", "winter", "warm"],
        status: "available"
      },
      {
        title: "Trench Coat",
        description: "Classic trench coat perfect for transitional weather. Timeless style.",
        category: "jackets",
        size: "s",
        condition: "good",
        type: "both",
        brand: "Burberry",
        materials: ["cotton", "recycled_polyester"],
        color: "tan",
        sustainabilityScore: 7,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["trench", "classic", "transitional", "elegant"],
        status: "available"
      },
      {
        title: "Bamboo Fiber Blazer",
        description: "Professional blazer made from bamboo fabric. Sustainable business wear.",
        category: "jackets",
        size: "l",
        condition: "like_new",
        type: "swap",
        brand: "Boody",
        materials: ["bamboo"],
        color: "navy",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["blazer", "bamboo", "professional", "sustainable"],
        status: "available"
      },
      {
        title: "Vintage Leather Bomber Jacket",
        description: "Classic bomber jacket with vintage leather. Timeless American style.",
        category: "jackets",
        size: "m",
        condition: "good",
        type: "donation",
        brand: "Alpha Industries",
        materials: ["leather", "nylon"],
        color: "brown",
        sustainabilityScore: 6,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["bomber", "vintage", "american", "classic"],
        status: "available"
      },
      {
        title: "Recycled Fleece Jacket",
        description: "Cozy fleece jacket made from recycled materials. Perfect for layering.",
        category: "jackets",
        size: "s",
        condition: "new",
        type: "both",
        brand: "Patagonia",
        materials: ["recycled_fleece"],
        color: "blue",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["fleece", "recycled", "cozy", "layering"],
        status: "available"
      },
      {
        title: "Organic Cotton Field Jacket",
        description: "Functional field jacket made from organic cotton. Multiple pockets for utility.",
        category: "jackets",
        size: "l",
        condition: "like_new",
        type: "swap",
        brand: "Filson",
        materials: ["organic_cotton", "wax"],
        color: "olive",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["field_jacket", "organic", "utility", "outdoor"],
        status: "available"
      },
      {
        title: "Tencel Rain Jacket",
        description: "Waterproof rain jacket made from Tencel fabric. Sustainable weather protection.",
        category: "jackets",
        size: "m",
        condition: "new",
        type: "donation",
        brand: "Stella McCartney",
        materials: ["tencel", "waterproof_membrane"],
        color: "yellow",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["rain", "tencel", "waterproof", "sustainable"],
        status: "available"
      },
      {
        title: "Vintage Corduroy Jacket",
        description: "Retro corduroy jacket with warm texture. Perfect for autumn styling.",
        category: "jackets",
        size: "s",
        condition: "good",
        type: "both",
        brand: "Gap",
        materials: ["corduroy", "cotton"],
        color: "rust",
        sustainabilityScore: 7,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["corduroy", "vintage", "autumn", "retro"],
        status: "available"
      },
      {
        title: "Recycled Wool Overcoat",
        description: "Elegant overcoat made from recycled wool. Sustainable formal outerwear.",
        category: "jackets",
        size: "l",
        condition: "like_new",
        type: "swap",
        brand: "Reformation",
        materials: ["recycled_wool"],
        color: "charcoal",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["overcoat", "recycled", "formal", "elegant"],
        status: "available"
      },
      {
        title: "Bamboo Fiber Parka",
        description: "Warm parka made from bamboo fibers. Sustainable winter protection.",
        category: "jackets",
        size: "m",
        condition: "new",
        type: "donation",
        brand: "Boody",
        materials: ["bamboo", "recycled_down"],
        color: "green",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["parka", "bamboo", "winter", "sustainable"],
        status: "available"
      },
      {
        title: "Vintage Denim Trucker Jacket",
        description: "Classic trucker jacket with vintage denim wash. American workwear heritage.",
        category: "jackets",
        size: "l",
        condition: "good",
        type: "both",
        brand: "Levi's",
        materials: ["denim", "cotton"],
        color: "blue",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1571651205322-3886f6af25a2?w=400"],
        owner: user._id,
        tags: ["trucker", "denim", "workwear", "american"],
        status: "available"
      },

      // SHOES (15 items)
      {
        title: "Classic Canvas Sneakers",
        description: "Timeless canvas sneakers in white color. Comfortable and versatile for everyday wear.",
        category: "shoes",
        size: "custom",
        condition: "good",
        type: "both",
        brand: "Converse",
        materials: ["canvas", "rubber"],
        color: "white",
        sustainabilityScore: 7,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["classic", "casual", "versatile", "comfortable"],
        status: "available"
      },
      {
        title: "Leather Ankle Boots",
        description: "Stylish leather ankle boots perfect for fall and winter. Durable and fashionable.",
        category: "shoes",
        size: "custom",
        condition: "like_new",
        type: "swap",
        brand: "Dr. Martens",
        materials: ["leather"],
        color: "brown",
        sustainabilityScore: 6,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["boots", "leather", "durable", "fashionable"],
        status: "available"
      },
      {
        title: "Recycled Running Shoes",
        description: "Athletic running shoes made from recycled materials. Perfect for eco-conscious runners.",
        category: "shoes",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Nike",
        materials: ["recycled_materials", "rubber"],
        color: "multicolor",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["recycled", "athletic", "eco-friendly", "performance"],
        status: "available"
      },
      {
        title: "Hemp Fiber Loafers",
        description: "Comfortable loafers made from sustainable hemp fibers. Natural and breathable.",
        category: "shoes",
        size: "custom",
        condition: "like_new",
        type: "both",
        brand: "Thought",
        materials: ["hemp"],
        color: "tan",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["loafers", "hemp", "comfortable", "natural"],
        status: "available"
      },
      {
        title: "Vintage Leather Boots",
        description: "Classic leather boots with vintage styling. Timeless and durable.",
        category: "shoes",
        size: "custom",
        condition: "good",
        type: "swap",
        brand: "Frye",
        materials: ["leather"],
        color: "brown",
        sustainabilityScore: 6,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["boots", "vintage", "leather", "durable"],
        status: "available"
      },
      {
        title: "Recycled Plastic Sandals",
        description: "Eco-friendly sandals made from recycled ocean plastic. Perfect for summer.",
        category: "shoes",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Adidas",
        materials: ["recycled_plastic", "rubber"],
        color: "blue",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["sandals", "recycled", "ocean_plastic", "summer"],
        status: "available"
      },
      {
        title: "Bamboo Fiber Dress Shoes",
        description: "Elegant dress shoes made from bamboo fibers. Sustainable formal footwear.",
        category: "shoes",
        size: "custom",
        condition: "like_new",
        type: "both",
        brand: "Boody",
        materials: ["bamboo"],
        color: "black",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["dress_shoes", "bamboo", "formal", "sustainable"],
        status: "available"
      },
      {
        title: "Organic Cotton Espadrilles",
        description: "Comfortable espadrilles made from organic cotton. Perfect for summer styling.",
        category: "shoes",
        size: "custom",
        condition: "good",
        type: "swap",
        brand: "Soludos",
        materials: ["organic_cotton", "jute"],
        color: "natural",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["espadrilles", "organic", "summer", "comfortable"],
        status: "available"
      },
      {
        title: "Recycled Leather High Tops",
        description: "Fashionable high-top sneakers made from recycled leather. Sustainable street style.",
        category: "shoes",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Veja",
        materials: ["recycled_leather", "rubber"],
        color: "white",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["high_tops", "recycled", "street_style", "fashionable"],
        status: "available"
      },
      {
        title: "Tencel Running Shoes",
        description: "Performance running shoes made from Tencel fabric. Sustainable athletic footwear.",
        category: "shoes",
        size: "custom",
        condition: "like_new",
        type: "both",
        brand: "Allbirds",
        materials: ["tencel", "recycled_rubber"],
        color: "gray",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["running", "tencel", "performance", "sustainable"],
        status: "available"
      },
      {
        title: "Vintage Suede Boots",
        description: "Classic suede boots with vintage styling. Perfect for autumn fashion.",
        category: "shoes",
        size: "custom",
        condition: "good",
        type: "swap",
        brand: "UGG",
        materials: ["suede", "sheepskin"],
        color: "tan",
        sustainabilityScore: 5,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["suede", "vintage", "autumn", "comfortable"],
        status: "available"
      },
      {
        title: "Recycled Canvas Slip-Ons",
        description: "Easy slip-on shoes made from recycled canvas. Convenient and sustainable.",
        category: "shoes",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Vans",
        materials: ["recycled_canvas", "rubber"],
        color: "black",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["slip_on", "recycled", "convenient", "casual"],
        status: "available"
      },
      {
        title: "Cork Sandals",
        description: "Eco-friendly sandals with cork footbed. Natural and comfortable.",
        category: "shoes",
        size: "custom",
        condition: "like_new",
        type: "both",
        brand: "Birkenstock",
        materials: ["cork", "natural_rubber"],
        color: "brown",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["sandals", "cork", "natural", "comfortable"],
        status: "available"
      },
      {
        title: "Recycled Wool Slippers",
        description: "Cozy slippers made from recycled wool. Perfect for sustainable lounging.",
        category: "shoes",
        size: "custom",
        condition: "good",
        type: "swap",
        brand: "Patagonia",
        materials: ["recycled_wool"],
        color: "gray",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["slippers", "recycled", "cozy", "lounging"],
        status: "available"
      },
      {
        title: "Bamboo Fiber Flip-Flops",
        description: "Simple flip-flops made from bamboo fibers. Sustainable beach footwear.",
        category: "shoes",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Reef",
        materials: ["bamboo", "rubber"],
        color: "blue",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["flip_flops", "bamboo", "beach", "sustainable"],
        status: "available"
      },
      {
        title: "Vintage Leather Oxfords",
        description: "Classic Oxford shoes with vintage leather. Timeless formal footwear.",
        category: "shoes",
        size: "custom",
        condition: "good",
        type: "both",
        brand: "Allen Edmonds",
        materials: ["leather"],
        color: "brown",
        sustainabilityScore: 6,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
        owner: user._id,
        tags: ["oxfords", "vintage", "formal", "classic"],
        status: "available"
      },

      // ACCESSORIES (15 items)
      {
        title: "Leather Crossbody Bag",
        description: "Elegant leather crossbody bag perfect for daily use. Timeless design with modern functionality.",
        category: "accessories",
        size: "custom",
        condition: "like_new",
        type: "both",
        brand: "Coach",
        materials: ["leather"],
        color: "brown",
        sustainabilityScore: 6,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["leather", "elegant", "practical", "timeless"],
        status: "available"
      },
      {
        title: "Silk Scarf Collection",
        description: "Beautiful silk scarf with artistic print. Perfect accessory for any outfit.",
        category: "accessories",
        size: "custom",
        condition: "like_new",
        type: "swap",
        brand: "Hermès",
        materials: ["silk"],
        color: "multicolor",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["silk", "luxury", "artistic", "versatile"],
        status: "available"
      },
      {
        title: "Recycled Tote Bag",
        description: "Eco-friendly tote bag made from recycled materials. Perfect for shopping and daily use.",
        category: "accessories",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Baggu",
        materials: ["recycled_materials"],
        color: "black",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["recycled", "eco-friendly", "practical", "sustainable"],
        status: "available"
      },
      {
        title: "Bamboo Fiber Watch",
        description: "Modern watch with strap made from bamboo fibers. Combines style with sustainability.",
        category: "accessories",
        size: "custom",
        condition: "like_new",
        type: "both",
        brand: "WeWOOD",
        materials: ["bamboo", "stainless_steel"],
        color: "natural",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1523275335688-e3809e01b0c4?w=400"],
        owner: user._id,
        tags: ["bamboo", "watch", "sustainable", "modern"],
        status: "available"
      },
      {
        title: "Vintage Leather Belt",
        description: "Classic leather belt with vintage buckle. Timeless accessory for any outfit.",
        category: "accessories",
        size: "custom",
        condition: "good",
        type: "swap",
        brand: "Gucci",
        materials: ["leather", "brass"],
        color: "brown",
        sustainabilityScore: 6,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["belt", "vintage", "leather", "classic"],
        status: "available"
      },
      {
        title: "Recycled Sunglasses",
        description: "Stylish sunglasses made from recycled ocean plastic. UV protection with sustainability.",
        category: "accessories",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Ray-Ban",
        materials: ["recycled_plastic", "glass"],
        color: "black",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1473496659199-fdc835453219?w=400"],
        owner: user._id,
        tags: ["sunglasses", "recycled", "uv_protection", "eco-friendly"],
        status: "available"
      },
      {
        title: "Hemp Fiber Wallet",
        description: "Durable wallet made from sustainable hemp fibers. Natural and long-lasting.",
        category: "accessories",
        size: "custom",
        condition: "like_new",
        type: "both",
        brand: "Patagonia",
        materials: ["hemp"],
        color: "green",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["wallet", "hemp", "durable", "sustainable"],
        status: "available"
      },
      {
        title: "Organic Cotton Beanie",
        description: "Cozy beanie made from organic cotton. Perfect for sustainable winter accessories.",
        category: "accessories",
        size: "custom",
        condition: "good",
        type: "swap",
        brand: "Patagonia",
        materials: ["organic_cotton"],
        color: "navy",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["beanie", "organic", "winter", "cozy"],
        status: "available"
      },
      {
        title: "Tencel Gloves",
        description: "Elegant gloves made from Tencel fabric. Sustainable luxury accessories.",
        category: "accessories",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Stella McCartney",
        materials: ["tencel"],
        color: "black",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["gloves", "tencel", "luxury", "sustainable"],
        status: "available"
      },
      {
        title: "Recycled Leather Backpack",
        description: "Functional backpack made from recycled leather. Sustainable and stylish.",
        category: "accessories",
        size: "custom",
        condition: "like_new",
        type: "both",
        brand: "Matt & Nat",
        materials: ["recycled_leather"],
        color: "black",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["backpack", "recycled", "functional", "stylish"],
        status: "available"
      },
      {
        title: "Vintage Silk Pocket Square",
        description: "Elegant silk pocket square with vintage pattern. Classic formal accessory.",
        category: "accessories",
        size: "custom",
        condition: "good",
        type: "swap",
        brand: "Hermès",
        materials: ["silk"],
        color: "red",
        sustainabilityScore: 8,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["pocket_square", "vintage", "silk", "formal"],
        status: "available"
      },
      {
        title: "Bamboo Fiber Hat",
        description: "Stylish hat made from bamboo fibers. Sustainable sun protection.",
        category: "accessories",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Boody",
        materials: ["bamboo"],
        color: "natural",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["hat", "bamboo", "sun_protection", "sustainable"],
        status: "available"
      },
      {
        title: "Recycled Phone Case",
        description: "Protective phone case made from recycled materials. Eco-friendly tech accessory.",
        category: "accessories",
        size: "custom",
        condition: "like_new",
        type: "both",
        brand: "Pela",
        materials: ["recycled_plastic", "plant_based"],
        color: "blue",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["phone_case", "recycled", "tech", "eco-friendly"],
        status: "available"
      },
      {
        title: "Organic Cotton Scarf",
        description: "Warm scarf made from certified organic cotton. Sustainable winter accessory.",
        category: "accessories",
        size: "custom",
        condition: "good",
        type: "swap",
        brand: "Eileen Fisher",
        materials: ["organic_cotton"],
        color: "gray",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["scarf", "organic", "winter", "warm"],
        status: "available"
      },
      {
        title: "Recycled Metal Jewelry",
        description: "Elegant jewelry set made from recycled metals. Sustainable luxury accessories.",
        category: "accessories",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Catbird",
        materials: ["recycled_silver", "recycled_gold"],
        color: "silver",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["jewelry", "recycled", "luxury", "sustainable"],
        status: "available"
      },
      {
        title: "Hemp Fiber Socks",
        description: "Comfortable socks made from sustainable hemp fibers. Natural and breathable.",
        category: "accessories",
        size: "custom",
        condition: "like_new",
        type: "both",
        brand: "Thought",
        materials: ["hemp", "organic_cotton"],
        color: "natural",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["socks", "hemp", "comfortable", "natural"],
        status: "available"
      },

      // OTHER (10 items)
      {
        title: "Vintage Sunglasses",
        description: "Classic retro-style sunglasses with UV protection. Timeless accessory for any look.",
        category: "other",
        size: "custom",
        condition: "good",
        type: "both",
        brand: "Ray-Ban",
        materials: ["plastic", "glass"],
        color: "black",
        sustainabilityScore: 7,
        images: ["https://images.unsplash.com/photo-1473496659199-fdc835453219?w=400"],
        owner: user._id,
        tags: ["vintage", "accessories", "classic", "uv_protection"],
        status: "available"
      },
      {
        title: "Organic Cotton Belt",
        description: "Sustainable belt made from organic cotton. Perfect for completing any eco-conscious outfit.",
        category: "other",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Patagonia",
        materials: ["organic_cotton"],
        color: "brown",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1473496659199-fdc835453219?w=400"],
        owner: user._id,
        tags: ["organic", "sustainable", "accessories", "eco-friendly"],
        status: "available"
      },
      {
        title: "Recycled Watch",
        description: "Modern watch with strap made from recycled materials. Combines style with sustainability.",
        category: "other",
        size: "custom",
        condition: "like_new",
        type: "swap",
        brand: "Nordgreen",
        materials: ["recycled_materials", "stainless_steel"],
        color: "silver",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1523275335688-e3809e01b0c4?w=400"],
        owner: user._id,
        tags: ["recycled", "watch", "accessories", "sustainable"],
        status: "available"
      },
      {
        title: "Bamboo Phone Stand",
        description: "Eco-friendly phone stand made from sustainable bamboo. Perfect for desk use.",
        category: "other",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Bamboo Basics",
        materials: ["bamboo"],
        color: "natural",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1523275335688-e3809e01b0c4?w=400"],
        owner: user._id,
        tags: ["bamboo", "phone_stand", "desk", "sustainable"],
        status: "available"
      },
      {
        title: "Recycled Yoga Mat",
        description: "Eco-friendly yoga mat made from recycled materials. Sustainable fitness equipment.",
        category: "other",
        size: "custom",
        condition: "like_new",
        type: "both",
        brand: "Manduka",
        materials: ["recycled_rubber"],
        color: "purple",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400"],
        owner: user._id,
        tags: ["yoga", "recycled", "fitness", "eco-friendly"],
        status: "available"
      },
      {
        title: "Hemp Fiber Notebook",
        description: "Sustainable notebook made from hemp fiber paper. Eco-friendly stationery.",
        category: "other",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Hemp Heritage",
        materials: ["hemp", "recycled_paper"],
        color: "natural",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1523275335688-e3809e01b0c4?w=400"],
        owner: user._id,
        tags: ["notebook", "hemp", "stationery", "sustainable"],
        status: "available"
      },
      {
        title: "Recycled Water Bottle",
        description: "Reusable water bottle made from recycled materials. Sustainable hydration.",
        category: "other",
        size: "custom",
        condition: "good",
        type: "swap",
        brand: "S'well",
        materials: ["recycled_stainless_steel"],
        color: "blue",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1523275335688-e3809e01b0c4?w=400"],
        owner: user._id,
        tags: ["water_bottle", "recycled", "hydration", "sustainable"],
        status: "available"
      },
      {
        title: "Organic Cotton Tote Bag",
        description: "Large tote bag made from certified organic cotton. Perfect for shopping.",
        category: "other",
        size: "custom",
        condition: "like_new",
        type: "both",
        brand: "Eileen Fisher",
        materials: ["organic_cotton"],
        color: "natural",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
        owner: user._id,
        tags: ["tote_bag", "organic", "shopping", "sustainable"],
        status: "available"
      },
      {
        title: "Bamboo Cutlery Set",
        description: "Portable cutlery set made from sustainable bamboo. Perfect for eco-friendly dining.",
        category: "other",
        size: "custom",
        condition: "new",
        type: "donation",
        brand: "Bamboo Switch",
        materials: ["bamboo"],
        color: "natural",
        sustainabilityScore: 10,
        images: ["https://images.unsplash.com/photo-1523275335688-e3809e01b0c4?w=400"],
        owner: user._id,
        tags: ["cutlery", "bamboo", "portable", "eco-friendly"],
        status: "available"
      },
      {
        title: "Recycled Glass Candle",
        description: "Scented candle in recycled glass container. Eco-friendly home fragrance.",
        category: "other",
        size: "custom",
        condition: "new",
        type: "both",
        brand: "P.F. Candle Co.",
        materials: ["recycled_glass", "soy_wax"],
        color: "clear",
        sustainabilityScore: 9,
        images: ["https://images.unsplash.com/photo-1523275335688-e3809e01b0c4?w=400"],
        owner: user._id,
        tags: ["candle", "recycled", "home_fragrance", "eco-friendly"],
        status: "available"
      }
    ];

    // Clear existing items first
    await Item.deleteMany({});
    console.log('Cleared existing items');

    // Add all 100 items to database
    let addedCount = 0;
    for (const itemData of items100) {
      const item = new Item(itemData);
      await item.save();
      console.log(`Added item: ${item.title} (${item.category})`);
      addedCount++;
    }

    console.log(`\n✅ Successfully added ${addedCount} items across all categories!`);
    console.log(`Total items in database: ${await Item.countDocuments()}`);

    // Show category breakdown
    const categories = ['shirts', 'pants', 'dresses', 'jackets', 'shoes', 'accessories', 'other'];
    console.log('\n📊 Items by category:');
    for (const category of categories) {
      const count = await Item.countDocuments({ category });
      console.log(`${category}: ${count} items`);
    }

    // Show sustainability score breakdown
    console.log('\n🌱 Sustainability Score Distribution:');
    for (let score = 6; score <= 10; score++) {
      const count = await Item.countDocuments({ sustainabilityScore: score });
      console.log(`Score ${score}: ${count} items`);
    }

  } catch (error) {
    console.error('Error adding items:', error);
  } finally {
    mongoose.disconnect();
  }
}

add100Items();
